project:
  type: book
  output-dir: docs
book:
  title: Analysing Genomic Data with dartRverse
  author: Bernd Gruber, Diana Robledo-Ruiz, Arthur Georges, Elise Furlan, Luis Mijangos, and Emily Stringer
  date: January 2026
  chapters:
  - index.qmd
  - schedule.qmd
  - inst/tutorials/W11/W11.rmd
  - inst/tutorials/W13/W13.rmd
format:
  html:
    toc: true
    toc-depth: 4
    theme: cosmo
    css:
    - dartR_style.css
    number-depth: 1
    link-external-icon: true
    link-external-newwindow: true
execute:
  cache: false
editor: visual
